/*
MySQL Data Transfer
Source Host: localhost
Source Database: jobseeker
Target Host: localhost
Target Database: jobseeker
Date: 2013/9/28 16:54:00
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for industry
-- ----------------------------
CREATE TABLE `industry` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(100) default NULL,
  `parent` varchar(100) NOT NULL default 'Transport and Logistics',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=328 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for personal_skills
-- ----------------------------
CREATE TABLE `personal_skills` (
  `id` int(11) NOT NULL auto_increment,
  `skill` varchar(100) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for tech_skills
-- ----------------------------
CREATE TABLE `tech_skills` (
  `id` int(11) NOT NULL auto_increment,
  `skill` varchar(100) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=152 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `industry` VALUES ('1', 'General', '0');
INSERT INTO `industry` VALUES ('2', 'Accounting', '0');
INSERT INTO `industry` VALUES ('3', 'Administration and Office Support', '0');
INSERT INTO `industry` VALUES ('4', 'Advertising', '0');
INSERT INTO `industry` VALUES ('5', 'Arts', '0');
INSERT INTO `industry` VALUES ('6', 'Media', '0');
INSERT INTO `industry` VALUES ('7', 'Banking and Financial Services', '0');
INSERT INTO `industry` VALUES ('8', 'Call Centre and Customer Service', '0');
INSERT INTO `industry` VALUES ('9', 'CEO and General Management', '0');
INSERT INTO `industry` VALUES ('10', 'Community Services and Development', '0');
INSERT INTO `industry` VALUES ('11', 'Construction', '0');
INSERT INTO `industry` VALUES ('12', 'Consulting and Strategy', '0');
INSERT INTO `industry` VALUES ('13', 'Design and Architecture', '0');
INSERT INTO `industry` VALUES ('14', 'Education and Training', '0');
INSERT INTO `industry` VALUES ('15', 'Engineering', '0');
INSERT INTO `industry` VALUES ('16', 'Environment & Sustainability', '0');
INSERT INTO `industry` VALUES ('17', 'Farming, Animals and Conservation', '0');
INSERT INTO `industry` VALUES ('18', 'Government', '0');
INSERT INTO `industry` VALUES ('19', 'Healthcare and Medical', '0');
INSERT INTO `industry` VALUES ('20', 'Hospitality and Tourism', '0');
INSERT INTO `industry` VALUES ('21', 'Human Resources and Recruitment', '0');
INSERT INTO `industry` VALUES ('22', 'Information and Communication Technology', '0');
INSERT INTO `industry` VALUES ('23', 'Insurance', '0');
INSERT INTO `industry` VALUES ('24', 'Legal', '0');
INSERT INTO `industry` VALUES ('25', 'Manufacturing', '0');
INSERT INTO `industry` VALUES ('26', 'Marketing and Communications', '0');
INSERT INTO `industry` VALUES ('27', 'Mining, Resources and Energy', '0');
INSERT INTO `industry` VALUES ('28', 'NGOs and Charities', '0');
INSERT INTO `industry` VALUES ('29', 'Real Estate and Property', '0');
INSERT INTO `industry` VALUES ('30', 'Retail and Consumer Products', '0');
INSERT INTO `industry` VALUES ('31', 'Sales', '0');
INSERT INTO `industry` VALUES ('32', 'Science and Technology', '0');
INSERT INTO `industry` VALUES ('33', 'Self-Employment', '0');
INSERT INTO `industry` VALUES ('34', 'Sport and Recreation', '0');
INSERT INTO `industry` VALUES ('35', 'Trades and Services', '0');
INSERT INTO `industry` VALUES ('36', 'Transport and Logistics', '0');
INSERT INTO `industry` VALUES ('37', 'Analyst', 'General');
INSERT INTO `industry` VALUES ('38', 'Any Subclassification', 'General');
INSERT INTO `industry` VALUES ('39', 'Intern', 'General');
INSERT INTO `industry` VALUES ('40', 'Manager', 'General');
INSERT INTO `industry` VALUES ('41', 'Other', 'General');
INSERT INTO `industry` VALUES ('42', 'Project Management', 'General');
INSERT INTO `industry` VALUES ('43', 'Supervisor', 'General');
INSERT INTO `industry` VALUES ('44', 'Account and Relationship Management', 'Accounting');
INSERT INTO `industry` VALUES ('45', 'Accounts Officer/Clerks', 'Accounting');
INSERT INTO `industry` VALUES ('46', 'Accounts Payable', 'Accounting');
INSERT INTO `industry` VALUES ('47', 'Accounts Receivable/Credit Control', 'Accounting');
INSERT INTO `industry` VALUES ('48', 'Actuarial', 'Accounting');
INSERT INTO `industry` VALUES ('49', 'Agency Account Management', 'Accounting');
INSERT INTO `industry` VALUES ('50', 'Analysts', 'Accounting');
INSERT INTO `industry` VALUES ('51', 'Assessment', 'Accounting');
INSERT INTO `industry` VALUES ('52', 'Assistant Accountants', 'Accounting');
INSERT INTO `industry` VALUES ('53', 'Audit - External', 'Accounting');
INSERT INTO `industry` VALUES ('54', 'Audit - Internal', 'Accounting');
INSERT INTO `industry` VALUES ('55', 'Book Keeping', 'Accounting');
INSERT INTO `industry` VALUES ('56', 'Cost Accounting', 'Accounting');
INSERT INTO `industry` VALUES ('57', 'Financial Accounting and Reporting', 'Accounting');
INSERT INTO `industry` VALUES ('58', 'Financial Managers and Controllers', 'Accounting');
INSERT INTO `industry` VALUES ('59', 'Fund Administration', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('60', 'Administration ', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('61', 'Administrative Assistants', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('62', 'Company Secretaries', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('63', 'Data Entry', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('64', 'Office Management', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('65', 'Organisational Development', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('66', 'Payroll', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('67', 'Personal Assistant and Secretarial', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('68', 'Receptionists', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('69', 'Records Management and Document Correction', 'Administration and Office Support');
INSERT INTO `industry` VALUES ('70', 'Art Direction', 'Arts');
INSERT INTO `industry` VALUES ('71', 'Gallery Management', 'Arts');
INSERT INTO `industry` VALUES ('72', 'Illustration and Animation', 'Arts');
INSERT INTO `industry` VALUES ('73', 'Models', 'Arts');
INSERT INTO `industry` VALUES ('74', 'Performing Arts', 'Arts');
INSERT INTO `industry` VALUES ('75', 'Photography', 'Arts');
INSERT INTO `industry` VALUES ('76', 'Analysis and Reporting', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('77', 'Analysts', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('78', 'Banking - Business', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('79', 'Banking - Corporate and Institutional', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('80', 'Banking - Retail/Branch', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('81', 'Banking and Finance Law', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('82', 'Brokerage', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('83', 'Corporate Finance and Investment Banking', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('84', 'Credit', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('85', 'Financial Planning', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('86', 'Insolvency and Corporate Recovery', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('87', 'Mortgages', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('88', 'Stockbroking and Trading', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('89', 'Underwriting', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('90', 'Valuation', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('91', 'Wealth Management', 'Banking and Financial Services');
INSERT INTO `industry` VALUES ('108', 'Board Appointments', 'CEO and General Management');
INSERT INTO `industry` VALUES ('109', 'Body Corporate and Facilities Management', 'CEO and General Management');
INSERT INTO `industry` VALUES ('110', 'Business Development', 'CEO and General Management');
INSERT INTO `industry` VALUES ('111', 'Business Services and Corporate Advisory', 'CEO and General Management');
INSERT INTO `industry` VALUES ('112', 'Business Unit Manager', 'CEO and General Management');
INSERT INTO `industry` VALUES ('113', 'Business/Systems Analysis', 'CEO and General Management');
INSERT INTO `industry` VALUES ('114', 'CEO', 'CEO and General Management');
INSERT INTO `industry` VALUES ('115', 'Commercial Sales, Leasing and Property Management', 'CEO and General Management');
INSERT INTO `industry` VALUES ('116', 'COO and MD', 'CEO and General Management');
INSERT INTO `industry` VALUES ('117', 'Corporate Development', 'CEO and General Management');
INSERT INTO `industry` VALUES ('118', 'Deparment/Assistant Manager', 'CEO and General Management');
INSERT INTO `industry` VALUES ('119', 'Event Management', 'CEO and General Management');
INSERT INTO `industry` VALUES ('120', 'Internal Management', 'CEO and General Management');
INSERT INTO `industry` VALUES ('121', 'Planning and Scheduling', 'CEO and General Management');
INSERT INTO `industry` VALUES ('122', 'Store Management', 'CEO and General Management');
INSERT INTO `industry` VALUES ('123', 'Community Development', 'Community Services and Development');
INSERT INTO `industry` VALUES ('124', 'Library Services and Information Manager', 'Community Services and Development');
INSERT INTO `industry` VALUES ('125', 'Multicultural Services', 'Community Services and Development');
INSERT INTO `industry` VALUES ('126', 'Consulting - All Areas', 'Consulting and Strategy');
INSERT INTO `industry` VALUES ('127', 'Management and Change Consultancy', 'Consulting and Strategy');
INSERT INTO `industry` VALUES ('128', 'Media Strategy', 'Consulting and Strategy');
INSERT INTO `industry` VALUES ('129', 'Risk Consulting', 'Consulting and Strategy');
INSERT INTO `industry` VALUES ('130', 'Strategy and Planning', 'Consulting and Strategy');
INSERT INTO `industry` VALUES ('131', 'Architects', 'Design and Architecture');
INSERT INTO `industry` VALUES ('132', 'Architectural Drafting', 'Design and Architecture');
INSERT INTO `industry` VALUES ('133', 'Architecture', 'Design and Architecture');
INSERT INTO `industry` VALUES ('134', 'Fashion and Textile Design', 'Design and Architecture');
INSERT INTO `industry` VALUES ('135', 'Graphic Design', 'Design and Architecture');
INSERT INTO `industry` VALUES ('136', 'Industrial Design', 'Design and Architecture');
INSERT INTO `industry` VALUES ('137', 'Interior Design', 'Design and Architecture');
INSERT INTO `industry` VALUES ('138', 'Pattern Makers and Garment Technicians', 'Design and Architecture');
INSERT INTO `industry` VALUES ('139', 'Coaching and Instruction', 'Education and Training');
INSERT INTO `industry` VALUES ('140', 'Student Services', 'Education and Training');
INSERT INTO `industry` VALUES ('141', 'Teaching - Early Childhood', 'Education and Training');
INSERT INTO `industry` VALUES ('142', 'Teaching - Primary', 'Education and Training');
INSERT INTO `industry` VALUES ('143', 'Teaching - Secondary', 'Education and Training');
INSERT INTO `industry` VALUES ('144', 'Teaching - Tertiary', 'Education and Training');
INSERT INTO `industry` VALUES ('145', 'Teaching - Vocational', 'Education and Training');
INSERT INTO `industry` VALUES ('146', 'Teaching Aides and Special Needs', 'Education and Training');
INSERT INTO `industry` VALUES ('147', 'Tutoring', 'Education and Training');
INSERT INTO `industry` VALUES ('148', 'Aerospace Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('149', 'Automotive Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('150', 'Building Services Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('151', 'Chemical Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('152', 'Civil/Structural Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('153', 'Electrical Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('154', 'Engineering Drafting', 'Engineering');
INSERT INTO `industry` VALUES ('155', 'Environmental Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('156', 'Field Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('157', 'Hardware Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('158', 'Industrial Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('159', 'Materials Handling Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('160', 'Mechanical Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('161', 'Network Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('162', 'Process Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('163', 'Project Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('164', 'Software Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('165', 'Surveying', 'Engineering');
INSERT INTO `industry` VALUES ('166', 'Systems Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('167', 'Water and Waste Engineering', 'Engineering');
INSERT INTO `industry` VALUES ('168', 'Environmental, Earth and Geosciences', 'Environment & Sustainability');
INSERT INTO `industry` VALUES ('169', 'Environmental Services', 'Environment & Sustainability');
INSERT INTO `industry` VALUES ('170', 'Environmental and Sustainability Consulting', 'Environment & Sustainability');
INSERT INTO `industry` VALUES ('171', 'Agronomy and Farm Services', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('172', 'Butchers', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('173', 'Conservation, Parks and Wildlife', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('174', 'Farm Management', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('175', 'Fishing and Aquaculture', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('176', 'Veterinary Services and Animal Welfare', 'Farming, Animals and Conservation');
INSERT INTO `industry` VALUES ('177', 'Aged and Disability Support', 'Government');
INSERT INTO `industry` VALUES ('178', 'Air Force', 'Government');
INSERT INTO `industry` VALUES ('179', 'Army', 'Government');
INSERT INTO `industry` VALUES ('180', 'Child Welfare and Family Services', 'Government');
INSERT INTO `industry` VALUES ('181', 'Medical Services', 'Government');
INSERT INTO `industry` VALUES ('182', 'Navy', 'Government');
INSERT INTO `industry` VALUES ('183', 'Policy, Planning and Regulation', 'Government');
INSERT INTO `industry` VALUES ('184', 'Power Generation and Distribution', 'Government');
INSERT INTO `industry` VALUES ('185', 'Biotechnology and Genetics', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('186', 'Chinese Medicine', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('187', 'Chiropractic and Osteopathic', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('188', 'Client and Sales Administration', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('189', 'Clinical/Medical Research', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('190', 'Dental', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('191', 'Dieticians', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('192', 'Fitness and Personal Training', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('193', 'General Practitioners', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('194', 'Medical Administration', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('195', 'Medical Imaging', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('196', 'Medical Specialists', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('197', 'Natural Therapies and Alternative Medicine', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('198', 'Nursing', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('199', 'Optical', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('200', 'Pathology', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('201', 'Pharmaceuticals and Medical Devices', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('202', 'Pharmacy', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('203', 'Physiotherapy and Rehabilitation', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('204', 'Psychology, Counselling and Social Work', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('205', 'Research and Fellowships', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('206', 'Speech Therapy', 'Healthcare and Medical');
INSERT INTO `industry` VALUES ('207', 'Bakers and Pastry Chef', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('208', 'Bar and Beverage Staff', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('209', 'Chef/Cooks', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('210', 'Front Office and Guest Services', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('211', 'Hotel Manager', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('212', 'Restaurant Manager', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('213', 'Tour Guide', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('214', 'Travel Agent/Consultant', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('215', 'Waiting Staff', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('216', 'Winery and Viticulture', 'Hospitality and Tourism');
INSERT INTO `industry` VALUES ('217', 'Employment Services', 'HR');
INSERT INTO `industry` VALUES ('218', 'Industrial and Employee Relations', 'HR');
INSERT INTO `industry` VALUES ('219', 'Recruitment - Agency', 'HR');
INSERT INTO `industry` VALUES ('220', 'Recruitment - Internal', 'HR');
INSERT INTO `industry` VALUES ('221', 'Workplace Training and Assessment', 'HR');
INSERT INTO `industry` VALUES ('222', 'Database Development and Administration', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('223', 'Developers and Programmers', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('224', 'IT Support', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('225', 'Network and Systems Administration', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('226', 'Systems Accounting and IT Audit', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('227', 'Telecommunications', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('228', 'Web and Interaction Design', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('229', 'Web Development and Production', 'Information and Communication Technology');
INSERT INTO `industry` VALUES ('230', 'Claims', 'Insurance');
INSERT INTO `industry` VALUES ('231', 'Compliance and Risk', 'Insurance');
INSERT INTO `industry` VALUES ('232', 'Construction Law', 'Legal');
INSERT INTO `industry` VALUES ('233', 'Corporate and Commercial Law', 'Legal');
INSERT INTO `industry` VALUES ('234', 'Criminal and Civil Law', 'Legal');
INSERT INTO `industry` VALUES ('235', 'Employment Law', 'Legal');
INSERT INTO `industry` VALUES ('236', 'Environmental and Planning Law', 'Legal');
INSERT INTO `industry` VALUES ('237', 'Family Law', 'Legal');
INSERT INTO `industry` VALUES ('238', 'Insurance Law', 'Legal');
INSERT INTO `industry` VALUES ('239', 'Intellectual Property Law', 'Legal');
INSERT INTO `industry` VALUES ('240', 'Law Clerks and Paralegals', 'Legal');
INSERT INTO `industry` VALUES ('241', 'Legal Practice Management', 'Legal');
INSERT INTO `industry` VALUES ('242', 'Legal Secretaries', 'Legal');
INSERT INTO `industry` VALUES ('243', 'Litigation and Dispute Resolution', 'Legal');
INSERT INTO `industry` VALUES ('244', 'Personal Injury Law', 'Legal');
INSERT INTO `industry` VALUES ('245', 'Property Law', 'Legal');
INSERT INTO `industry` VALUES ('246', 'Tax Law', 'Legal');
INSERT INTO `industry` VALUES ('247', 'Brand Management', 'Marketing');
INSERT INTO `industry` VALUES ('248', 'Digital and Search Marketing', 'Marketing');
INSERT INTO `industry` VALUES ('249', 'Direct Marketing and CRM', 'Marketing');
INSERT INTO `industry` VALUES ('250', 'Market Rearch and Analysis', 'Marketing');
INSERT INTO `industry` VALUES ('251', 'Marketing Assistants/Coordinators', 'Marketing');
INSERT INTO `industry` VALUES ('252', 'Marketing Communications', 'Marketing');
INSERT INTO `industry` VALUES ('253', 'Editing and Publishing', 'Media');
INSERT INTO `industry` VALUES ('254', 'Journalism and Writing', 'Media');
INSERT INTO `industry` VALUES ('255', 'Printing and Publishing Services', 'Media');
INSERT INTO `industry` VALUES ('256', 'Public Relations and Corporate Affairs', 'Media');
INSERT INTO `industry` VALUES ('257', 'Mining - Drill and Blast', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('258', 'Mining - Engineering and Maintenance', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('259', 'Mining - Exploration and Geoscience', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('260', 'Mining Operations', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('261', 'Mining Processing', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('262', 'Oil and Gas - Drilling', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('263', 'Oil and Gas - Engineering and Maintenence', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('264', 'Oil and Gas - Exploration and Geoscience', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('265', 'Oil and Gas - Production and Refinement', 'Mining, Resources and Energy');
INSERT INTO `industry` VALUES ('266', 'Fund Administration', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('267', 'Fundraising', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('268', 'Funds Management', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('269', 'Policy, Planning and Regulation', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('270', 'Project Management', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('271', 'Research', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('272', 'Volunteer Coordination and Support', 'NGOs and Charities');
INSERT INTO `industry` VALUES ('273', 'Property Development', 'Real Estate and Property');
INSERT INTO `industry` VALUES ('274', 'Property Management', 'Real Estate and Property');
INSERT INTO `industry` VALUES ('275', 'Residential Leasing', 'Real Estate and Property');
INSERT INTO `industry` VALUES ('276', 'Transport and Logistics', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('277', 'Testing and Quality Assurance', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('278', 'Sales Representative', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('279', 'Sales Coordinator', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('280', 'Sales', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('281', 'Purchasing', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('282', 'Merchandisers', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('283', 'Inventory', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('284', 'Import/Export', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('285', 'Customer Service', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('286', 'Customer Service', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('287', 'Commercial Sales, Leasing and Property Management', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('288', 'Client Services', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('289', 'Client and Sales Administration', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('290', 'Aviation Industry', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('291', 'Airlines', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('292', 'Account Manager', 'Retail and Consumer Products');
INSERT INTO `industry` VALUES ('293', 'Biological and Biomedical Sciences', 'Science and Technology');
INSERT INTO `industry` VALUES ('294', 'Chemistry and Physics', 'Science and Technology');
INSERT INTO `industry` VALUES ('295', 'Computer Operators', 'Science and Technology');
INSERT INTO `industry` VALUES ('296', 'Environmental, Earth and Geosciences', 'Science and Technology');
INSERT INTO `industry` VALUES ('297', 'Food Technology and Safety', 'Science and Technology');
INSERT INTO `industry` VALUES ('298', 'Health and Safety', 'Science and Technology');
INSERT INTO `industry` VALUES ('299', 'Laboratory and Technical Services', 'Science and Technology');
INSERT INTO `industry` VALUES ('300', 'Materials Sciences', 'Science and Technology');
INSERT INTO `industry` VALUES ('301', 'Mathematics, Statistics and Information Sciences', 'Science and Technology');
INSERT INTO `industry` VALUES ('302', 'Natural Resources and Water', 'Science and Technology');
INSERT INTO `industry` VALUES ('303', 'Quality Assurance and Control', 'Science and Technology');
INSERT INTO `industry` VALUES ('304', 'Research and Fellowships', 'Science and Technology');
INSERT INTO `industry` VALUES ('305', 'Building Trades', 'Trades and Services');
INSERT INTO `industry` VALUES ('306', 'Carpentry', 'Trades and Services');
INSERT INTO `industry` VALUES ('307', 'Cleaning Services', 'Trades and Services');
INSERT INTO `industry` VALUES ('308', 'Courier and Postal Services', 'Trades and Services');
INSERT INTO `industry` VALUES ('309', 'Electricians', 'Trades and Services');
INSERT INTO `industry` VALUES ('310', 'Floristry', 'Trades and Services');
INSERT INTO `industry` VALUES ('311', 'Gardening and Landscaping', 'Trades and Services');
INSERT INTO `industry` VALUES ('312', 'Hair and Beauty', 'Trades and Services');
INSERT INTO `industry` VALUES ('313', 'Landscape Architecture', 'Trades and Services');
INSERT INTO `industry` VALUES ('314', 'Machine Maintenance', 'Trades and Services');
INSERT INTO `industry` VALUES ('315', 'Machinists', 'Trades and Services');
INSERT INTO `industry` VALUES ('316', 'Nannies and Babysitters', 'Trades and Services');
INSERT INTO `industry` VALUES ('317', 'Plumbers', 'Trades and Services');
INSERT INTO `industry` VALUES ('318', 'Security', 'Trades and Services');
INSERT INTO `industry` VALUES ('319', 'Technicians', 'Trades and Services');
INSERT INTO `industry` VALUES ('320', 'Fleet Management', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('321', 'Freight and Cargo Forwarding', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('322', 'Plant and Machinery', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('323', 'Programming and Production', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('324', 'Rail and Maritime Transport', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('325', 'Road Transport', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('326', 'Urban Design and Planning', 'Transport and Logistics');
INSERT INTO `industry` VALUES ('327', 'Warehousing, Storage and Distribution', 'Transport and Logistics');
INSERT INTO `personal_skills` VALUES ('1', 'Accuracy and attention to detail');
INSERT INTO `personal_skills` VALUES ('2', 'Business management skills');
INSERT INTO `personal_skills` VALUES ('3', 'Calm under pressure');
INSERT INTO `personal_skills` VALUES ('4', 'Commitment');
INSERT INTO `personal_skills` VALUES ('5', 'Conceptual Thinking');
INSERT INTO `personal_skills` VALUES ('6', 'Confidence');
INSERT INTO `personal_skills` VALUES ('7', 'Consistency and Reliability');
INSERT INTO `personal_skills` VALUES ('8', 'Creative thinking skills');
INSERT INTO `personal_skills` VALUES ('9', 'Crisis management skills');
INSERT INTO `personal_skills` VALUES ('10', 'Critical thinking skills');
INSERT INTO `personal_skills` VALUES ('11', 'Customer service skills');
INSERT INTO `personal_skills` VALUES ('12', 'Decision-making skills');
INSERT INTO `personal_skills` VALUES ('13', 'Determination');
INSERT INTO `personal_skills` VALUES ('14', 'Discipline');
INSERT INTO `personal_skills` VALUES ('15', 'Empathy');
INSERT INTO `personal_skills` VALUES ('16', 'Financial analysis skills');
INSERT INTO `personal_skills` VALUES ('17', 'Flexibility');
INSERT INTO `personal_skills` VALUES ('18', 'Human Awareness');
INSERT INTO `personal_skills` VALUES ('19', 'Initiative');
INSERT INTO `personal_skills` VALUES ('20', 'International experience');
INSERT INTO `personal_skills` VALUES ('21', 'Interpersonal communication skills');
INSERT INTO `personal_skills` VALUES ('22', 'IT skills and literacy');
INSERT INTO `personal_skills` VALUES ('23', 'Job Ethic');
INSERT INTO `personal_skills` VALUES ('24', 'Leadership skills');
INSERT INTO `personal_skills` VALUES ('25', 'Mentoring Abilities');
INSERT INTO `personal_skills` VALUES ('26', 'Networking skills');
INSERT INTO `personal_skills` VALUES ('27', 'Objective Listening');
INSERT INTO `personal_skills` VALUES ('28', 'Observational skills');
INSERT INTO `personal_skills` VALUES ('29', 'Organizational and planning skills');
INSERT INTO `personal_skills` VALUES ('30', 'Persistence');
INSERT INTO `personal_skills` VALUES ('31', 'Personal Drive');
INSERT INTO `personal_skills` VALUES ('32', 'Practical Thinking');
INSERT INTO `personal_skills` VALUES ('33', 'Presentation skills');
INSERT INTO `personal_skills` VALUES ('34', 'Proactive Thinking');
INSERT INTO `personal_skills` VALUES ('35', 'Problem analysis skills');
INSERT INTO `personal_skills` VALUES ('36', 'Project management skills');
INSERT INTO `personal_skills` VALUES ('37', 'Public speaking skills');
INSERT INTO `personal_skills` VALUES ('38', 'Relationship Building');
INSERT INTO `personal_skills` VALUES ('39', 'Research skills');
INSERT INTO `personal_skills` VALUES ('40', 'Resourcefulness');
INSERT INTO `personal_skills` VALUES ('41', 'Risk taking');
INSERT INTO `personal_skills` VALUES ('42', 'Sensitivity to Others');
INSERT INTO `personal_skills` VALUES ('43', 'Teaching skills');
INSERT INTO `personal_skills` VALUES ('44', 'Teamwork skills');
INSERT INTO `personal_skills` VALUES ('45', 'Theoretical Problem Solving');
INSERT INTO `personal_skills` VALUES ('46', 'Time Management skills');
INSERT INTO `personal_skills` VALUES ('47', 'Verbal communication skills');
INSERT INTO `personal_skills` VALUES ('48', 'Versatility and flexibility');
INSERT INTO `personal_skills` VALUES ('49', 'Willingness to learn');
INSERT INTO `tech_skills` VALUES ('1', 'Accounts Management');
INSERT INTO `tech_skills` VALUES ('2', 'Adobe (Photoshop, Dreamweaver, Illustrator)');
INSERT INTO `tech_skills` VALUES ('3', 'Auditing Financial Reports');
INSERT INTO `tech_skills` VALUES ('4', 'Blog Management');
INSERT INTO `tech_skills` VALUES ('5', 'Child Care');
INSERT INTO `tech_skills` VALUES ('6', 'Cold Calling');
INSERT INTO `tech_skills` VALUES ('7', 'Computer Operating Systems');
INSERT INTO `tech_skills` VALUES ('8', 'Customer Management');
INSERT INTO `tech_skills` VALUES ('9', 'Customer Service');
INSERT INTO `tech_skills` VALUES ('10', 'Database Engineering');
INSERT INTO `tech_skills` VALUES ('11', 'Debugging');
INSERT INTO `tech_skills` VALUES ('12', 'DHCP');
INSERT INTO `tech_skills` VALUES ('13', 'DNAS');
INSERT INTO `tech_skills` VALUES ('14', 'Economic Analysis');
INSERT INTO `tech_skills` VALUES ('15', 'Editing');
INSERT INTO `tech_skills` VALUES ('16', 'Financial Analysis');
INSERT INTO `tech_skills` VALUES ('17', 'Flash');
INSERT INTO `tech_skills` VALUES ('18', 'Graphic Design');
INSERT INTO `tech_skills` VALUES ('19', 'Hospitality Training');
INSERT INTO `tech_skills` VALUES ('20', 'HTML Skills');
INSERT INTO `tech_skills` VALUES ('21', 'Java Programming');
INSERT INTO `tech_skills` VALUES ('22', 'Knowledge of Legislation and Regulation');
INSERT INTO `tech_skills` VALUES ('23', 'Legal Research');
INSERT INTO `tech_skills` VALUES ('24', 'Managerial and Supervising Skills');
INSERT INTO `tech_skills` VALUES ('25', 'Market Research');
INSERT INTO `tech_skills` VALUES ('26', 'Marketing');
INSERT INTO `tech_skills` VALUES ('27', 'Microsoft');
INSERT INTO `tech_skills` VALUES ('28', 'Modeling');
INSERT INTO `tech_skills` VALUES ('29', 'MySQL Database Management');
INSERT INTO `tech_skills` VALUES ('30', 'Oracle Management');
INSERT INTO `tech_skills` VALUES ('31', 'Policy Setting');
INSERT INTO `tech_skills` VALUES ('32', 'Programming');
INSERT INTO `tech_skills` VALUES ('33', 'Project Management');
INSERT INTO `tech_skills` VALUES ('34', 'Public Speaking');
INSERT INTO `tech_skills` VALUES ('35', 'Quantitative Reports');
INSERT INTO `tech_skills` VALUES ('36', 'Raising funds');
INSERT INTO `tech_skills` VALUES ('37', 'Rehabilitation');
INSERT INTO `tech_skills` VALUES ('38', 'Research Skills');
INSERT INTO `tech_skills` VALUES ('39', 'Sales');
INSERT INTO `tech_skills` VALUES ('40', 'Secretarial Skills');
INSERT INTO `tech_skills` VALUES ('41', 'SEO Optimization');
INSERT INTO `tech_skills` VALUES ('42', 'Social Media Management');
INSERT INTO `tech_skills` VALUES ('43', 'Software Engineering');
INSERT INTO `tech_skills` VALUES ('44', 'Statistics');
INSERT INTO `tech_skills` VALUES ('45', 'Strategic Planning');
INSERT INTO `tech_skills` VALUES ('46', 'Surveying');
INSERT INTO `tech_skills` VALUES ('47', 'TCP/IP');
INSERT INTO `tech_skills` VALUES ('48', 'Teaching (Junior School-High School)');
INSERT INTO `tech_skills` VALUES ('49', 'Teaching (Kindergarten-Junior School)');
INSERT INTO `tech_skills` VALUES ('50', 'Teaching (Tertiary)');
INSERT INTO `tech_skills` VALUES ('51', 'Telemarketing');
INSERT INTO `tech_skills` VALUES ('52', 'Translation');
INSERT INTO `tech_skills` VALUES ('53', 'Troubleshooting');
INSERT INTO `tech_skills` VALUES ('54', 'Unix Operating Systems');
INSERT INTO `tech_skills` VALUES ('55', 'Web design');
INSERT INTO `tech_skills` VALUES ('56', 'Web Server Administration');
INSERT INTO `tech_skills` VALUES ('57', 'Writing (Media)');
INSERT INTO `tech_skills` VALUES ('58', 'Sabre (ticketing program)');
INSERT INTO `tech_skills` VALUES ('59', 'Primavera (project management software)');
INSERT INTO `tech_skills` VALUES ('60', 'Read/Interpret blueprints');
INSERT INTO `tech_skills` VALUES ('61', 'Medical Image Interpretation ');
INSERT INTO `tech_skills` VALUES ('62', 'Peri Programming Language');
INSERT INTO `tech_skills` VALUES ('63', 'XML - Extensible Markup Language ');
INSERT INTO `tech_skills` VALUES ('64', 'C++ Programming Language');
INSERT INTO `tech_skills` VALUES ('65', 'Linux Operating System');
INSERT INTO `tech_skills` VALUES ('66', 'Mac OSX');
INSERT INTO `tech_skills` VALUES ('67', 'Human Resource Management ');
INSERT INTO `tech_skills` VALUES ('68', 'Travelport Ticketing System');
INSERT INTO `tech_skills` VALUES ('69', 'Amadeus ');
INSERT INTO `tech_skills` VALUES ('70', 'Lexis Nexis Casebase');
INSERT INTO `tech_skills` VALUES ('71', 'Westlaw case research ');
INSERT INTO `tech_skills` VALUES ('72', 'Administrative Skills');
INSERT INTO `tech_skills` VALUES ('73', 'Sample Presentation (medical)');
INSERT INTO `tech_skills` VALUES ('74', 'Laboratory Skills (medical)');
INSERT INTO `tech_skills` VALUES ('75', 'electrocardiogram equipment use');
INSERT INTO `tech_skills` VALUES ('76', 'Computer Aided Design (CAD)');
INSERT INTO `tech_skills` VALUES ('77', 'Solidworks (CAD)');
INSERT INTO `tech_skills` VALUES ('78', 'Catia (CAD)');
INSERT INTO `tech_skills` VALUES ('79', 'PIC Design');
INSERT INTO `tech_skills` VALUES ('80', 'Stock Drive Products');
INSERT INTO `tech_skills` VALUES ('81', 'J W Winco');
INSERT INTO `tech_skills` VALUES ('82', 'W M Berg');
INSERT INTO `tech_skills` VALUES ('83', 'FEA software');
INSERT INTO `tech_skills` VALUES ('84', 'Anodizing Skills (Engineering)');
INSERT INTO `tech_skills` VALUES ('85', 'Plating Skills (Engineering)');
INSERT INTO `tech_skills` VALUES ('86', 'Analytical Skills');
INSERT INTO `tech_skills` VALUES ('87', 'Legal Drafting');
INSERT INTO `tech_skills` VALUES ('88', 'Legal Writing');
INSERT INTO `tech_skills` VALUES ('89', 'Chartered Geologer Certificate ');
INSERT INTO `tech_skills` VALUES ('90', 'Customer Relationship Management (CRM)');
INSERT INTO `tech_skills` VALUES ('91', 'SAP AG (CRM)');
INSERT INTO `tech_skills` VALUES ('92', 'salesforce.com (CRM)');
INSERT INTO `tech_skills` VALUES ('93', 'Microsoft CRM (CRM)');
INSERT INTO `tech_skills` VALUES ('94', ' Amdocs (CRM)');
INSERT INTO `tech_skills` VALUES ('95', 'Bloomberg Professional Software');
INSERT INTO `tech_skills` VALUES ('96', 'TEFL / TESOL');
INSERT INTO `tech_skills` VALUES ('97', 'CELTA');
INSERT INTO `tech_skills` VALUES ('98', '3PL Warehouse Manager (logistics)');
INSERT INTO `tech_skills` VALUES ('99', 'Appian DirectRoute (logistics)');
INSERT INTO `tech_skills` VALUES ('100', 'Apptricity Supply Chain Management (logistics)');
INSERT INTO `tech_skills` VALUES ('101', 'PackManager CoPacking Software (logisitics)');
INSERT INTO `tech_skills` VALUES ('102', 'Awery Airline Management Software (logisitics)');
INSERT INTO `tech_skills` VALUES ('103', '20/20 Delivery Software (logisitics)');
INSERT INTO `tech_skills` VALUES ('104', '4S eTrans (logistics)');
INSERT INTO `tech_skills` VALUES ('105', '3PLink (logistics)');
INSERT INTO `tech_skills` VALUES ('106', 'Microsoft Dynamics (management)');
INSERT INTO `tech_skills` VALUES ('107', 'Basecamp (cloud based management)');
INSERT INTO `tech_skills` VALUES ('108', 'Genius Project (management)');
INSERT INTO `tech_skills` VALUES ('109', 'Microsoft Project (management)');
INSERT INTO `tech_skills` VALUES ('110', 'OneDesk (management)');
INSERT INTO `tech_skills` VALUES ('111', 'Planbox (management)');
INSERT INTO `tech_skills` VALUES ('112', 'Eloqua (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('113', 'Infusionsoft (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('114', 'Hubspot (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('115', 'Teradata / Aprimo (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('116', 'Unica (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('117', 'Marketo (marketing automation software)');
INSERT INTO `tech_skills` VALUES ('118', 'Interpreting ');
INSERT INTO `tech_skills` VALUES ('119', 'WordPress Software');
INSERT INTO `tech_skills` VALUES ('120', 'Banking Software');
INSERT INTO `tech_skills` VALUES ('121', 'HSK Mandarin Chinese Level');
INSERT INTO `tech_skills` VALUES ('122', 'Google Docs');
INSERT INTO `tech_skills` VALUES ('123', 'Google Drive');
INSERT INTO `tech_skills` VALUES ('124', 'OpenOffice');
INSERT INTO `tech_skills` VALUES ('125', 'Intuit (accounting software)');
INSERT INTO `tech_skills` VALUES ('126', 'sage (accounting software)');
INSERT INTO `tech_skills` VALUES ('127', 'Multiview Enterprise .NET n10 (accounting software)');
INSERT INTO `tech_skills` VALUES ('128', 'NetSuite');
INSERT INTO `tech_skills` VALUES ('129', 'Xero (accounting software)');
INSERT INTO `tech_skills` VALUES ('130', 'Microsoft VisioA (computer programming)');
INSERT INTO `tech_skills` VALUES ('131', 'AdobeAcrobat ');
INSERT INTO `tech_skills` VALUES ('132', 'Skype for business');
INSERT INTO `tech_skills` VALUES ('133', 'LinkedIn');
INSERT INTO `tech_skills` VALUES ('134', 'Social Media Marketing');
INSERT INTO `tech_skills` VALUES ('135', 'Microsoft Access');
INSERT INTO `tech_skills` VALUES ('136', 'Lotus Approach');
INSERT INTO `tech_skills` VALUES ('137', 'Corel Paradox');
INSERT INTO `tech_skills` VALUES ('138', 'Lotus Organixer (Personal information manager)');
INSERT INTO `tech_skills` VALUES ('139', 'Sidekick by Starfish');
INSERT INTO `tech_skills` VALUES ('140', 'Microsoft Exchange (groupware)');
INSERT INTO `tech_skills` VALUES ('141', 'Netscape Communicator (groupware)');
INSERT INTO `tech_skills` VALUES ('142', 'Callabra (groupwise)');
INSERT INTO `tech_skills` VALUES ('143', 'Novell Groupwise (groupwise)');
INSERT INTO `tech_skills` VALUES ('144', 'Corel QuattroPro (electronic Spreadsheets)');
INSERT INTO `tech_skills` VALUES ('145', 'Lotus 1-2-3 (electronic spreadsheets)');
INSERT INTO `tech_skills` VALUES ('146', 'Adobe PageMaker (Digital Publishing)');
INSERT INTO `tech_skills` VALUES ('147', 'QuarkXPress (Digital Publishing)');
INSERT INTO `tech_skills` VALUES ('148', 'POS system (retail)');
INSERT INTO `tech_skills` VALUES ('149', 'Transaction Processing Systems');
INSERT INTO `tech_skills` VALUES ('150', 'Process Control Systems');
INSERT INTO `tech_skills` VALUES ('151', 'Cold Calling');

#2013-11-12
INSERT INTO  `industry` (`id` ,`name` ,`parent`)
VALUES (NULL ,  'Brand Management',  'Marketing and Communications'), 
(NULL ,  'Digital and Search Marketing',  'Marketing and Communications'),
(NULL ,  'Direct Marketing and CRM',  'Marketing and Communications'),
(NULL ,  'Market Resarch and Analysis',  'Marketing and Communications'),
(NULL ,  'Marketing Assistants/Coordinators',  'Marketing and Communications'),
(NULL ,  'Marketing Communications',  'Marketing and Communications');